animal = "  chanCHito happy   "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("CH"))
print(animal.find("cH"))
print(animal.replace("nCH", "E"))
print("nCH" in animal)
print("nCH" not in animal)
